#!/usr/bin/env python3
"""Write the cash-null audit reconciliation artifacts (checked by tests/test_gate_metrics.py).

Usage: .venv/bin/python scripts/reconcile_cash_null_audit.py
Outputs under data/processed/cash_null_audit/:
  reconciliation.csv, rf_fallback_share.csv, trial_counts.json, reconciliation.md,
  site_sharpe.json (every Sharpe the Pages site shows: excess of BIL + legacy rf = 0)
Input committed alongside: shortlist_strategy_returns.csv (see data/processed/cash_null_audit/README.md).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from usa_etf_features import cash_null_audit as cna  # noqa: E402

OUT = ROOT / "data" / "processed" / "cash_null_audit"


def _txt(x):
    return x.replace("-", "−") if isinstance(x, str) else ""


def _fmt(x, nd=4):
    return "" if x is None or x != x else f"{x:.{nd}f}".replace("-", "−")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    rec = cna.reconciliation_table()
    fb = cna.fallback_shares()
    counts = cna.trial_counts()
    rec.to_csv(OUT / "reconciliation.csv", index=False, float_format="%.6f", lineterminator="\n")
    fb.to_csv(OUT / "rf_fallback_share.csv", index=False, float_format="%.6f", lineterminator="\n")
    (OUT / "trial_counts.json").write_text(json.dumps(
        {"helper": counts, "memo": cna.MEMO_COUNTS}, indent=2, sort_keys=True) + "\n")
    lines = ["# Cash-null audit reconciliation (shared gate helper vs Quant memo, 2026-09-26)", "",
             "rf = BIL priced monthly total return from BIL's first full month (2007-06); FRED TB3MS/1200 before.",
             "Sharpe_exBIL = mean(r − rf)·12 / (std(r − rf)·√12). Sharpe_rf0 = legacy (rf = 0), CAGR / vol.",
             "Reproduces = matches the memo's printed value to its printed precision and the audit script's",
             "4-decimal value to 1e-4. Generated by `scripts/reconcile_cash_null_audit.py`.", "",
             "| Gate | Strategy | Window (n) | TB3MS fallback | Sharpe ex-BIL (helper) | Memo ex-BIL | "
             "Legacy rf=0 (helper) | Memo rf=0 | Reproduces |",
             "|---|---|---|---|---|---|---|---|---|"]
    for r in rec[rec.in_memo].itertuples():
        mark = "yes" if r.reproduces else f"no: {r.note}"
        lines.append(f"| {r.gate} | {r.strategy} | {r.window} ({r.n_months}) | {r.rf_fallback_share:.1%} | "
                     f"{_fmt(r.Sharpe_exBIL)} | {_txt(r.memo_exBIL)} | "
                     f"{_fmt(r.Sharpe_rf0_legacy)} | {_txt(r.memo_rf0)} | {mark} |")
    lines += ["", "## Trial counts", "", "| Statement | Helper | Memo |", "|---|---|---|"]
    for k, v in counts.items():
        lines.append(f"| {k} | {v.replace('-', '−')} | {cna.MEMO_COUNTS[k].replace('-', '−')} |")
    lines += ["", "## Risk-free fallback share per window", "",
              "| Gate | Window | Months | TB3MS fallback months | Fallback share | BIL share | Memo BIL share |",
              "|---|---|---|---|---|---|---|"]
    for r in fb.itertuples():
        lines.append(f"| {r.gate} | {r.start}..{r.end} | {r.n_months} | {r.fallback_months} | "
                     f"{r.fallback_share:.1%} | {r.bil_share:.1%} | {r.memo_bil_share_pct}% |")
    (OUT / "reconciliation.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (OUT / "site_sharpe.json").write_text(json.dumps(cna.site_sharpe_figures(), indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
